# Do not change the values below!
# If a change is required copy appropriate lines to the /local/config.local.py file and change the values there.

SECRET_KEY = 'please_change_@187%0^&'

# Database connection
DB_HOST = 'localhost'
DB_PORT = 3306
DB_NAME = 'test'
DB_USER = 'test'
DB_PASSWORD = 'test'

# Security
SECURITY_PASSWORD_SALT = '9873313545127551081313677346265396239529'

SECURITY_FLASH_MESSAGES = True
SECURITY_PASSWORD_LENGTH_MIN = 8

SECURITY_POST_LOGIN_VIEW = '/'
SECURITY_POST_LOGOUT_VIEW = '/'

SECURITY_REGISTERABLE = True
SECURITY_SEND_REGISTER_EMAIL = False
SECURITY_POST_REGISTER_VIEW = 'security.login'
SECURITY_USERNAME_ENABLE = False
SECURITY_USERNAME_REQUIRED = False

SECURITY_CONFIRMABLE = False
SECURITY_CHANGEABLE = False

SECURITY_RECOVERABLE = False
SECURITY_TWO_FACTOR = False
SECURITY_TWO_FACTOR_REQUIRED = False
SECURITY_TWO_FACTOR_ENABLED_METHODS = ['email']
SECURITY_UNIFIED_SIGNIN = False
SECURITY_PASSWORDLESS = False
SECURITY_TRACKABLE = True
SECURITY_WEBAUTHN = True
SECURITY_MULTI_FACTOR_RECOVERY_CODES = False
